-- Schema as it existed when Flyway was introduced (previously created by Hibernate's ddl-auto=update).
-- Databases that already have these tables are baselined at version 1 and skip this file.

create sequence app_user_seq start with 1 increment by 50;

create table app_user (
    id       bigint       not null,
    email    varchar(255),
    password varchar(255),
    username varchar(255),
    primary key (id)
);

create table favorites (
    id         bigint generated by default as identity,
    event_id   varchar(255) not null,
    event_name varchar(255),
    user_id    bigint       not null references app_user (id),
    primary key (id)
);

create table reviews (
    id         bigint generated by default as identity,
    event_id   varchar(255) not null,
    user_id    bigint       not null references app_user (id),
    rating     integer      not null check (rating >= 1 and rating <= 5),
    comment    varchar(1000),
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table password_reset_tokens (
    id         bigint generated by default as identity,
    token_hash varchar(64)              not null unique,
    user_id    bigint                   not null references app_user (id),
    expires_at timestamp(6) with time zone not null,
    primary key (id)
);
